---
applications:
- name: telegraf_agent_vsphere-1
  memory: 256M
  disk_quota: 512M
  health-check-type: process
  docker:
    image: <docker registry url>/telegraf:vsphere_v0.1
  services:
    - log-drain
    - secrets
    - telegraf-vsphere-default
    - telegraf-vsphere-in
    - telegraf-vsphere-wavefront-out
